# Generated by Django 2.1 on 2019-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=10)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
