# Generated by Django 2.1 on 2019-11-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='festival',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
