# Generated by Django 2.1 on 2019-12-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_auto_20191203_1812'),
        ('festivals', '0002_auto_20191202_2202'),
    ]

    operations = [
    ]
