# Generated by Django 2.1 on 2019-12-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_merge_20191203_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='best',
            field=models.IntegerField(default=0),
        ),
    ]
