# Generated by Django 2.1 on 2019-12-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20191202_2203'),
        ('festivals', '0005_festival_best'),
    ]

    operations = [
    ]
