# Generated by Django 2.1 on 2019-12-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_merge_20191203_2148'),
        ('festivals', '0007_auto_20191203_2258'),
    ]

    operations = [
    ]
