# Generated by Django 2.1 on 2019-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_delete_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='notification',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
