# Generated by Django 2.1 on 2019-11-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('festival', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=20)),
                ('usercount', models.IntegerField(default=0)),
            ],
        ),
    ]
