# Generated by Django 2.1 on 2019-11-28 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191126_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='festival',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='category',
            new_name='leader_id',
        ),
        migrations.AddField(
            model_name='groups',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='groups',
            name='ticket',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='groups',
            name='usercount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
