# Generated by Django 2.1 on 2019-12-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='ticket',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
