# Generated by Django 2.1 on 2019-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20191128_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='festival_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='groups',
            name='festival_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
