# Generated by Django 2.1 on 2019-11-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20191128_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_authenticated',
            field=models.IntegerField(default=0),
        ),
    ]
