# Generated by Django 2.1 on 2019-12-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_comment_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='groupname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notify',
            name='groupname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
