# Generated by Django 2.1 on 2019-11-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20191129_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='maxcount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='usercount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
