# Generated by Django 2.1 on 2019-12-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20191203_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
