# Generated by Django 2.1 on 2019-11-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=50)),
                ('place', models.CharField(default='', max_length=30)),
                ('price', models.IntegerField(blank=True, default='', null=True)),
                ('lineup', models.TextField(default='')),
                ('post', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
