# Generated by Django 2.1 on 2019-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='post',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='lineup',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='time',
        ),
        migrations.AddField(
            model_name='festival',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
