# Generated by Django 2.1 on 2019-12-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20191203_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='pic',
            new_name='poster',
        ),
    ]
