# Generated by Django 2.1 on 2019-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_merge_20191203_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
