# Generated by Django 2.1 on 2019-12-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0008_merge_20191204_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
